### ISSUE TITLE
Missing argument exception 

### ISSUE THREAD

**Issue by viertelb** [rachmadaniHaryono/we-get#34]
`we-get -s TEXT` currently leads to an exception, I suspect because a webpage cannot be reached.

```
pi@raspberrypi:~ $ we-get --search "test"
# error:  'jackett_rss' - no results..
Error when opening following url.bay' ...
https://apibay.org/q.php?q=test
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/we_get/core/we_get.py", line 176, in run
    items = run.main(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/we_get/modules/the_pirate_bay.py", line 74, in main
    return run.search()
  File "/home/pi/.local/lib/python3.7/site-packages/we_get/modules/the_pirate_bay.py", line 58, in search
    data = self.module.http_get_request(url)
  File "/home/pi/.local/lib/python3.7/site-packages/we_get/core/module.py", line 39, in http_get_request
    raise err
  File "/home/pi/.local/lib/python3.7/site-packages/we_get/core/module.py", line 26, in http_get_request
    content = opener.open(url).read()
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/we-get", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/we_get/__init__.py", line 15, in main
    we_get.start()
  File "/home/pi/.local/lib/python3.7/site-packages/we_get/core/we_get.py", line 265, in start
    sel.run()
  File "/home/pi/.local/lib/python3.7/site-packages/we_get/core/we_get.py", line 178, in run
    msg_error(str(err))
TypeError: msg_error() missing 1 required positional argument: 'exit'

```

**Comment by rachmadaniHaryono** [comment]
try https://github.com/rachmadaniHaryono/we-get/commit/a8167f475b47c76f9d7bae618c98a892045571d9
