### ISSUE TITLE
Error on search

### ISSUE THREAD

**Issue by kahn10** [rachmadaniHaryono/we-get#35]
When attempting to do a search, I get a cryptic error. 
```
 we-get -s Goonies -t 1337x
Traceback (most recent call last):
  File "/home/conn/.local/bin/we-get", line 10, in <module>
    sys.exit(main())
  File "/home/conn/.local/lib/python3.7/site-packages/we_get/__init__.py", line 18, in main
    we_get.start()
  File "/home/conn/.local/lib/python3.7/site-packages/we_get/core/we_get.py", line 199, in start
    sel.run()
  File "/home/conn/.local/lib/python3.7/site-packages/we_get/core/we_get.py", line 157, in run
    from we_get.core.shell import shell
  File "/home/conn/.local/lib/python3.7/site-packages/we_get/core/shell.py", line 16, in <module>
    from we_get.core.style import we_get_prompt_style
  File "/home/conn/.local/lib/python3.7/site-packages/we_get/core/style.py", line 8, in <module>
    from prompt_toolkit.token import Token
ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (/home/conn/.local/lib/python3.7/site-packages/prompt_toolkit/token.py)
```
Tested both searching -t all and -t 1337x. Tested on both Debian on Windows (5.4.72-microsoft-standard-WSL2) and on Ubuntu Groovy on Google Cloud (5.8.0-1032-gcp).

**Comment by kahn10** [comment]
Confirmed that prompt_toolkit is installed on both systems:
```
pip3 install prompt_toolkit
Requirement already satisfied: prompt_toolkit in /home/conn/.local/lib/python3.7/site-packages (3.0.18)
Requirement already satisfied: wcwidth in /home/conn/.local/lib/python3.7/site-packages (from prompt_toolkit) (0.2.5)
```

**Comment by kahn10** [comment]
Solved by installing the most recent commit as referenced in this ticket:
https://github.com/rachmadaniHaryono/we-get/issues/29
