### ISSUE TITLE
Error when opening following url.bay' ...

### ISSUE THREAD

**Issue by immartian** [rachmadaniHaryono/we-get#37]
Error when opening following url.bay' ...
http://yts.ag/api/v2/list_movies.json?quality=720p&genre=all
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1414, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 918, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

**To Reproduce**
run `we-get --list`

**Expected behavior**
a full list

**Screenshots**
![image](https://user-images.githubusercontent.com/81030/127014260-d64bab91-a446-4ef9-ae74-7aa351fba953.png)

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.04.2 LTS

**Comment by rachmadaniHaryono** [comment]
can you visit the url with your browser?

**Comment by gulprun** [comment]
I have met the same issue here. Seems yts.ag is offline.

**Comment by gulprun** [comment]
I changed the line at yts.py: https://github.com/rachmadaniHaryono/we-get/blob/16bf73b31fbcc18b85d5ba1c948464530439f9bd/we_get/modules/yts.py#L9 to another mirror site and it worked.

**Comment by viertelb** [comment]
Login needed to use API?

**Comment by rachmadaniHaryono** [comment]
few hours ago url just fine but now it redirect me to `yts.mx` and error
